---

- debug: var=ansible_service_mgr

- name: install myservice systemd unit file
  template: src=supervisord.systemd.j2 dest=/etc/systemd/system/supervisord.service mode=0644
  when: ansible_service_mgr=="systemd"
  notify:
    - restart supervisord
  register: rs

- name: Make supervisord as system service
  template: src=supervisord.sysvinit.j2 dest="/etc/init.d/supervisord" mode=0755
  when: ansible_service_mgr=="sysvinit"
  notify:
    - restart supervisord

- name: Make supervisord as system service
  template: src=supervisord.upstart.j2 dest="/etc/init/supervisord" mode=0755
  when: ansible_service_mgr=="upstart"
  notify:
    - restart supervisord

- systemd:
  state: restarted
  daemon_reload: yes
  name: supervisord
  