---


- name: install myservice systemd unit file
  template: src=supervisord.service.j2 dest=/etc/systemd/system/supervisord.service mode=0644
  when: ansible_service_mgr=="systemd"
  notify:
    - restart supervisord
  register: rs

- systemd:
    state: restarted
    daemon_reload: yes
    name: supervisord
  when: ansible_service_mgr=="systemd" and rs|changed

- name: Make supervisord as system service
  template: src=supervisord.j2 dest="/etc/init.d/supervisord" mode=0755
  when: ansible_service_mgr=="upstart"
  notify:
    - restart supervisord

