---

- name: Install supervisor
  include: install.yml

- name: Install as Service
  include: install-service.yml

- name: Ensure supervisord started
  service: name={{ supervisor_service }} state=started